### PR TITLE
Rewrite Stage 1

### LINKED ISSUE #38: Sev2 Breaking defect spawner reference copy
`Mob` Object model referenced property SKSpriteNode.
`Mob` with `SpawnManager`.

Breaks when spawning the same `Mob`.

Deep-dive problem:
* `struct` `let` assign only shallow copies the reference to same SKNode. 
* addChild of same SKNode reference to the same SKScene reference causes NSException crash to AppDelegate.

### PR DESCRIPTION
**Pull request by slimlime**
Concept worked out for #37 Part 1
1. Scalable spawn positioning system + can see the UX impact with animations proportions.
Resolves #38

ToDo: 
2. Concise clear physics contact functionality

### CODE REVIEW

**Comment by slimlime** [comment]
@seant1 Hey-o. How are you?

Please skim last four commits ~ and let me know what you think (What silly things have I done that need fixing)? :fire::zap: 🖥  💻 🦆 :mango:🥭

**Review by seant1 — APPROVED** [review]
squeaky clean


- the process works

**Comment by slimlime** [comment]
_*the cousinsmango approve this message*_

**Comment by slimlime** [comment]
Fixes #37

**Pull request merged**
